imageio_ffmpeg/_utils.py

I removed ``LIB_DIR``, because it is not used anywhere.
I add ``bin_dir`` in the function, because it triggers an extraction of the binary (if applicable) and should not happen when importing the module. For instance, people might want to use their own exes anyway and not want to wait for pkg_resources to extract another one.
closes #7

use pkg_resources to get binary

---

imageio_ffmpeg/_io.py
tests/test_io.py

Possible solution/workaround for #13. This PR adds the 'ffmpeg_timeout' keyword argument to `write_frames` so the user can ask for imageio to wait longer for ffmpeg to finish. This is especially important when writing larger frames where ffmpeg may need more time.

Add 'ffmpeg_timeout' flag to write_frames

---

imageio_ffmpeg/_io.py
tasks.py
tests/test_io.py

* I tried reducing the buffersize of stdin, and using `stdin.flush`, but this has no effect on the wait time.
* Made the default timeout much longer (20s)
* Better message when ffmpeg is killed (tell user to increase `ffmpeg_timeout`)
* Handle case where Python gets interrupted during waiting for ffmpeg to finish.
* Clarify some invoke tasks by making them print some more info about what they're doing.
Related to #13. Builds on #14.

 Tweaks to killing ffmpeg on writing 

---

imageio_ffmpeg/_io.py
tests/test_io.py

```python
import imageio
imageio.get_reader(b'', 'ffmpeg')
```
The reader immediately raises the `OSError` exception.
The reader **hangs for 10s** and raises the `OSError` exception.
`read_frames` waiting from `log_catcher` for the header within the 10s timeout range. Invalid videos produce no header thereby `read_frames` hangs even when `log_catcher`'s thread was terminated.
https://github.com/imageio/imageio-ffmpeg/blob/master/imageio_ffmpeg/_io.py#L141-L144
Check if `log_catcher`'s thread was terminated in metadata extraction.

read_frames hangs on invalid video

---

imageio_ffmpeg/_utils.py

Hi, I have been using imageio-ffmpeg with imageio on Windows, however the module was flashing the ffmpeg executable's window with the _get_ffmpeg_exe()_ and _get_ffmpeg_version()_ commands.
So I changed the __utils.py_ file to no longer do this and was wondering if I could contribute to the main repository.

Stopped executable window from flashing on Windows

---

imageio_ffmpeg/_io.py
tests/test_io.py

Bug: `read_frames` read 2 frames as one from 
==
Code
===
```
import os
import tempfile
from urllib.request import urlopen
import imageio_ffmpeg
url = "https://raw.githubusercontent.com/imageio/imageio-binaries/master/images/realshort.mp4"
content = urlopen(url).read()
file_path = os.path.join(tempfile.gettempdir(), "cockatoo.mp4")
with open(file_path, "wb") as f:
f.write(content)
gen = imageio_ffmpeg.read_frames(file_path, pix_fmt="yuv420p")
meta = gen.__next__()
frames_count_meta = meta['fps'] * meta['duration']
frames = list(gen)
print(f'{frames_count_meta} vs {len(frames)}')
```
Expected
===
`36.024 vs 36`
Result
===
`36.024 vs 18`
Cause
===
`read_frames` can handle only bytes per pixel, but yuv 420 has 6 bytes per 4 pixels (12 bits per 1 pixel). By default `read_frames` read 3 bytes …

added bits_per_pixel parameter to read_frames

---

imageio_ffmpeg/_definitions.py

Cygwin is a hybrid between Windows and Unix.  It does not currently
provide ffmpeg as a package, so the user will have to rely on Windows
builds, such as the [Zeranoe](https://ffmpeg.zeranoe.com/builds/) ones.
Setting winNN can work with such an installation and a suitable path.
Issue: #26

Avoid exception under Cygwin

---

imageio_ffmpeg/_io.py

This is to fix #17, it's not clear to me why `p.communicate()` with a timeout still hangs, nor why `p.send_signal(signal.SIGINT)` doesn't cause a graceful exit.  But since they don't seem to work, and this is reading data, not writing it, seems fine to simply terminate the subprocess.
Is there any downside to this @almarklein?

Fix hang in read_frames fixes #17

---

imageio_ffmpeg/_io.py
imageio_ffmpeg/_utils.py
tests/test_io.py

* Support for pathlib.Path (and black formatting)
* Sets default `ffmpeg_timeout` to 0 (wait without timeout). Closes #30 
* Prevent sigint from propagating to ffmpeg. Closes #4 
* When interruping (ctrl-c, KeyBoardInterrupt, SystemExit) during reading or writing, we terminate ffmpeg without waiting.
* Fixes that we actually close ffmpeg nicely after reading, without hanging. Related to #17 and  #19.
* This also closes #20 (technically #19 already fixed the segfault, this PR makes sure we terminate ffmpeg in a nicer way).

Tweaks and fixes

---

imageio_ffmpeg/_io.py
tasks.py
tests/snippets.py
tests/test_io.py
tests/test_parsing.py
tests/test_special.py
tests/test_terminate.py
tests/testutils.py

* Removed a line in the part where `read_frames()` signals ffmpeg to quit, preventing "Invalid Argument" (Windows) and "Broken Pipe" (Linux) warnings. Previously we did not see these warnings because they were swallowed pre v0.4.0.
* Allow `ffmpeg_timeout` to be None.
* Refactored tests a bit. Added a test for threading, and added a script with some manual tests.

Fix Invalid Argument and Broken Pipe warnings, and more

---

imageio_ffmpeg/_io.py

Clean up a resource that otherwise leads to:
```
/home/larsoner/.local/lib/python3.8/site-packages/imageio/plugins/ffmpeg.py:531: ResourceWarning: unclosed file <_io.BufferedReader name=80>
self._write_gen.close()
```

FIX: Close resource

---

imageio_ffmpeg/_parsing.py

From https://docs.python.org/3/whatsnew/3.9.html:
> The isAlive() method of threading.Thread has been removed. It was deprecated since Python 3.8. Use is_alive() instead. (Contributed by Dong-hee Na in bpo-37804.)

Fix compatibility with python3.9

---

README.md
imageio_ffmpeg/_io.py
imageio_ffmpeg/_parsing.py
tests/test_io.py

This adds support for encoding with an audio stream from a file path along with an option to provide an output audio codec.
Strings `audio_path` and `audio_codec` can be provided to the `write_frames` method.
It outputs a warning but successfully encodes the video when the stream provided as `audio_path` has no audio stream.
It also adds an `audio_codec` key to the metadata when reading if an audio stream is present - with output gathered in a similar way to the video metadata.
Tried to keep it minimal; let me know if you want me to change anything.
#50

Add support for encoding with audio from a path

---

imageio_ffmpeg/_definitions.py

Add linux aarch64 wheel build support.
Related to https://github.com/imageio/imageio-ffmpeg/issues/52 @almarklein Could you please review this PR?

Add linux aarch64 wheel build support

---

imageio_ffmpeg/_parsing.py

Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10

---

README.md
imageio_ffmpeg/_utils.py

This is a workaround for a strange hang on fork() when `Popen` is called with
a `preexec_fn` (see #58). If the environment variable
`IMAGEIO_FFMPEG_NO_PREVENT_SIGINT` is not empty, `preexec_fn` is set to
None.

Optional disabling of `prevent_sigint`.

---

.github/workflows/ci.yml
imageio_ffmpeg/_io.py
tests/test_io.py

This should fix issue #61.
My initial inclination was to call `p.stderr.close()` directly after closing `stdout` and `stdin`, [here](https://github.com/imageio/imageio-ffmpeg/blob/v0.4.5/imageio_ffmpeg/_io.py#L244). However, that caused `Windows fatal exception: access violation` in `test_io.py`.

Fix issue 61: explicitly close stderr stream when read_frames exits

---

tasks.py

This is causing: https://github.com/imageio/imageio-ffmpeg/pull/65 to fail.

Lint task.py file with black

---

imageio_ffmpeg/_io.py
tests/test_io.py

I tried to leave the defaults the same. But if x264 isn't available (for example, maybe a user doesn't want GPL), then it will gracefully fallback onto other encoders.

Automatically find available h264 encoders and choose the best one according to our heuristics

---

imageio_ffmpeg/_parsing.py
tests/test_parsing.py

Closes https://github.com/imageio/imageio-ffmpeg/issues/78

Fix pix_format parser to capture formats that have commas within strings

---

imageio_ffmpeg/_definitions.py

When I was trying to run moviepy in a docker container (Docker for Mac on M1). I got the error:
`RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.`
Digging into the source of the issue, it was detecting the platform as `linux64` instead of `linuxaarch64`. manually patching this on my machine fixed it, so I thought I would upstream it.
I think it'll resolve https://github.com/imageio/imageio-ffmpeg/issues/71

detect m1 macs correctly for ffmpeg filenames

---

.github/FUNDING.yml

@almarklein ImageIO is now approved to receive donations via GitHub Sponsors. I've added a link in the main repo, but let's also add one here.

Add GH Sponsors Link

---

imageio_ffmpeg/__init__.py
imageio_ffmpeg/_definitions.py
imageio_ffmpeg/_io.py
imageio_ffmpeg/_parsing.py
imageio_ffmpeg/_utils.py
tasks.py
tests/snippets.py
tests/test_io.py
tests/test_special.py
tests/test_terminate.py
tests/testutils.py

1. Replaced `with warns(None) as warnings:` with a new syntax by importing the warnings module and `with warnings.catch_warnings(record=True) as warnings_:`. This turned one of the pytest warning to a pytest passed.
1. Fixed type from `FFMEG` to `FFMPEG`
2. Replaced the variable `i` with `_` for for-loops that do not utilize `i`
3. Replaced variable names with more descriptive ones: `w` -> `width`, `h` -> `height`, `p` -> `process`
1. Ran `isort .`
2. Ran `black .`

Updated deprecated test approach + minor changes

---

tasks.py

Really just to prevent errors when running the autoformatting locally for certain scenarios ...

Fix format

---

.github/workflows/ci.yml
tests/test_special.py

For some reason, the `test_threading()` test started failing on pypy. There does not seem to be a difference in the pypy version compared to the last CI-run that passed.

Check CI pypy

---

imageio_ffmpeg/_parsing.py
tests/test_parsing.py

Tis PR is to solve the issue mentioned in https://github.com/imageio/imageio/issues/949
Trying to set `meta["fps"]` to be the **`fps`** value parsed from ffmpeg banner of **the input video stream**, instead of the **`tbr`** value of the **output video stream**.
[Code Reference](https://github.com/imageio/imageio-ffmpeg/blob/77a3d85feeef431e2c8ad066eb7d1df08730337c/imageio_ffmpeg/_parsing.py#L165-L170)
Currently, we are setting `meta["fps"]` to prefer the **`tbr`** value of the **output video source**.
For example, for the ffmpeg banner below:
```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.2_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang …
```

correct `fps` parsing
